//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisdoeducative.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wisdoeducative.Application.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It looks like you&apos;ve selected a date in the future. Please choose a date that is today or earlier..
        /// </summary>
        internal static string DegreeDateFuture {
            get {
                return ResourceManager.GetString("DegreeDateFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It looks like this item already exists in the system..
        /// </summary>
        internal static string DuplicatedEntity {
            get {
                return ResourceManager.GetString("DuplicatedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! We couldn&apos;t find the item you&apos;re looking for..
        /// </summary>
        internal static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! We ran into an issue while trying to save the item&apos;s history..
        /// </summary>
        internal static string HistorySaveErrorMessage {
            get {
                return ResourceManager.GetString("HistorySaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! it looks like your selected dates are not valid, please check if the start date greater than the end date.
        /// </summary>
        internal static string InvalidEvaluationTaskDates {
            get {
                return ResourceManager.GetString("InvalidEvaluationTaskDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It looks like you&apos;re trying to assing more weight than the evaluation category has assigned..
        /// </summary>
        internal static string InvalidEvaluationTaskWeight {
            get {
                return ResourceManager.GetString("InvalidEvaluationTaskWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It looks like the pomodoro session has some invalid values..
        /// </summary>
        internal static string InvalidPomodoroSession {
            get {
                return ResourceManager.GetString("InvalidPomodoroSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! it looks like your reminder does not have the correct data..
        /// </summary>
        internal static string InvalidReminderData {
            get {
                return ResourceManager.GetString("InvalidReminderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! your total course weight cannot exceed 100..
        /// </summary>
        internal static string InvalidWeight {
            get {
                return ResourceManager.GetString("InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! There are no interests available.
        /// </summary>
        internal static string NoInterestsAvailable {
            get {
                return ResourceManager.GetString("NoInterestsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You must provide a study plan to retrive all it&apos;s terms.
        /// </summary>
        internal static string NoStudyPlanProvided {
            get {
                return ResourceManager.GetString("NoStudyPlanProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You must provide a study plan term.
        /// </summary>
        internal static string NotStudyPlanTermProvided {
            get {
                return ResourceManager.GetString("NotStudyPlanTermProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It looks like some details for this item are missing..
        /// </summary>
        internal static string NullProperties {
            get {
                return ResourceManager.GetString("NullProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You need to have more than 13 years old.
        /// </summary>
        internal static string RestrictedAgeError {
            get {
                return ResourceManager.GetString("RestrictedAgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Your study plan term needs to start after the start date of your degre.
        /// </summary>
        internal static string StudyPlanAfterCreationDate {
            get {
                return ResourceManager.GetString("StudyPlanAfterCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! The provided dates do not match with the schedule type of your degree.
        /// </summary>
        internal static string StudyPlanTermNotMatchWithSchedule {
            get {
                return ResourceManager.GetString("StudyPlanTermNotMatchWithSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! The dates for this study plan overlap with another term. Could you please pick different dates?.
        /// </summary>
        internal static string StudyTermOverlap {
            get {
                return ResourceManager.GetString("StudyTermOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It looks like there&apos;s already an account with this information..
        /// </summary>
        internal static string UserAlreadyExistsErrorMessage {
            get {
                return ResourceManager.GetString("UserAlreadyExistsErrorMessage", resourceCulture);
            }
        }
    }
}
